permalink: /articles/:title
description: Intelligent Random Stuff
tagline: Intelligent Random Stuff
title: Seun Martins
name: Seun Martins
email: seundotme@gmail.com
url:  http://impactmass.com
logo: "/assets/images/favicon.jpg"
cover: "/assets/images/background_image.jpg"
paginate: 7
author:
  name: Seun Martins
  email: seundotme@gmail.com
port: 3000
plugins: [jekyll-paginate]
future: true

# Build settings
markdown: kramdown
