# Permalinks
permalink:        /articles/:title
relative_permalinks: true
description: > # this means to ignore newlines until "email:"
   Intelligent random stuff
# Setup
title:            Seun Martins
name:            Seun Martins
tagline:          intelligent random stuff
email:            seundotme@gmail.com

#blog logo
logo: "assets/images/favicon.jpg"
# blog cover
cover: "assets/images/background_image.jpg"

#url:              http://getpoole.com
paginate:         5
baseurl:          ""
author:
  name:           Seun Martins
  url:            https://twitter.com/impactmass
  email:          seundotme@gmail.com

# Custom vars
#version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole
port:             3000

# Build settings
markdown: rdiscount
rdiscount:
  extensions: [smart]

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/impactmass
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:  facebook
    url: https://facebook.com/impactmass
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

# - icon: github
#   url:  https://github.com/dirkfabisch
#   desc: Fork me on github
#   share_url:
#   share_title:
#   share_link:

#  - icon:  google-plus
#    url: https://google.com/???
#    desc:  Add me on google+
#    share_url:
#    share_title:
#    share_link:

